language: cpp
compiler:
    - gcc
before_install:
    # disable rvm, use system Ruby
    - rvm reset
    - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "rake yast2-devtools yast2 yast2-packager yast2-storage yast2-bootloader ruby2.1-dev libaugeas-dev pkg-config" -g "rspec:3.3.0 yast-rake gettext simplecov coveralls cfa_grub2 cheetah"
script:
    - rake check:syntax
    - rake check:pot
    - COVERAGE=1 rake test:unit
    - sudo rake install
